DECLARE @counter int
SET @counter = 1

UPDATE players SET password ='nsb61l'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='96siA5k1LPdI'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='cUc90PE'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='n8DJ5My6I'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='u0DTUaG'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='9fiSxSmwGX'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='R0IYmBw'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='uzik5eUMoRdO'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='W7DbWSAjcgqL'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='G6AO4gF'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='tvDbmntx'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='q5d0LSagj'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='OnSvXg7'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='pRDWNt'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='6vRujF'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='gozR5p8ObL5Z'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='RJ8ZsC32g'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='IMEjCWDJ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='T35a2Hpp'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Yxm0Z1o9'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='dpPECTr0zq'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='rXicTqISMy'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='8yeuR7'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='xkHISRC'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='JKgwBB'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='lh514S3qMRD'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='rk2SHCA8'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ahFCCL'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='EV6z2eusms'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='NHcKOEc9a'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='6Cvm4Wu'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Qc9XKTqX5'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Mp4z8saaY'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='XTKq1OJN7JkL'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='JI9JDITxROoh'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='nlyqqM'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='STSjz1D'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='iHH5AJlb'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='A2Zmbqeu'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Il2qPVNzPqnY'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Sr3Xfhz0H'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='PVDRB2FZiCRC'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ztWmDKkSD3ve'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='O7YzNXB8CB'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Cw6EqvhvSpIQ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ZyMJI0J'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='OjMqXk'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='AfBoo2Tp'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Vzr09zx9gzL'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='PfhHGgMx'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='3vydgrKRw'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='k3u6bSOsFeY'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='LSdOChkO'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ZhjGNqFkH8C'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='SV2vxVu0bGV6'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='u3021T3a5V6'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='EdKxY3C'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='TX4JOmQqkkA'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='9p4cX3Afpnh'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='IU7ACYu'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='TTdo0p6DVOG'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='iAi4Zn'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='AZbT3WhSUY46'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='8Ynr9dTn0h0'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ESrw2f6K'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='waPcZMF9eL6'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Dg0T2QG'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='HAOly2'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='X3jiWqR'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='sRoqYUCVO'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='aoFk364aq2L'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='zASPRqfIGZIV'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='5OSMru'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='1HCr0t'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='yseDyrzYe'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='pllMTV'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='RWdQDlwq'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='CT0kuH3yJJO'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='1dsusW'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='uGCOF9f'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='9pmIFmzoHm'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='1Tj6X1QFbb'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='1i9KYr8EQbm'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='nwfYBEpm'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='N9C3n61xZ3i1'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='zhXMZhLWnj'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='c3Tl5WhC'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='86Kpepbke'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='a1pSP5ZaMV'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='lfpZeBtkZHdt'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='crCdgEOxWqAp'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='zw3C82no1j'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='9vfq8CVW'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='2flUIGIi7r3g'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='vnaUbU'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='F63cZqY'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='dHuuptng'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='37bAS9HG'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='bufSDF'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='jQen9zYKfCF'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='cE1ORCp'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ip0qfw'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='aEr1Ny'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ouWqhm'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='znAtogOk1'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='qFAFbYtuOZ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='QdaQds'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='S03ompZeVJo'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='joF04mD'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='lpG3bmf9hAie'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='7WdqyRw'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='NtjRVnejR'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='imH05Rfw1wlT'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='YlV0nqvQg'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='EB6kdSL'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='bRlWVmE4'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='vR18Ki4N'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='huGiYjhIm'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='5fwqkx9tv'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='7fOemQQRr4qD'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='bGFFjuLZisX'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='cP5tUtFUsB'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='70Ldwg0vb3Q3'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='lv1ka36jjiY'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='THfibJq'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='RF7mtace40B'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='9khuaxg1fmlc'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='yb0TcujUTaZ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='NLltVEdTa'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='h4bMM4LY'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='7Znf9j4zrsZ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='sD0jp43GuV'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='2PXhc5F51'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Bijiv4h'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Rvl6ngl'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Kq3ZTCm65'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='zCm6ngbg'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Bstt3ZFa'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='fxW7KOnaND'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='U5qywJ8TfMgC'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='H2E9uDia'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='1KMDwIONP'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='jb4YVcK'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='sAUpthL'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='cJps0jj'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='0soxQmCVzec'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='31cjWGS'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='7mg7Xaic'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ZY9CLQ4y'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Ku8PBB15Lnu'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='qlYGrgRSe'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='RlN3NovkHQ4w'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='FkXQU8KeRnX'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='zIXzQ0OJf'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='VyaokqDFzVcU'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='kTO5shgnIe9'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='YOnK9Lq'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ciyF71'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='HbAkzx0Pq'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='oqneEcwP8zch'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='xepeymgRBYlx'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='0LXQslSXJ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ActmXuLqv2q'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Zkxb7w6iyO8R'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='HcUGrRhJ9'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='T9R2pzFHHFS'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='2trOBoLZ8'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='9ZwAZh'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ZEfKmpax'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='035glTz'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='SgbgZUVxGHC4'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='zHP2lXugkzl0'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='LqBfRbwXW6w'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='K3643oyD'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='jgAe2F'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='CPRH62VJZ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='7a5rMaU'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='8Snwbi3S'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='sADYxmx87'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='9JbqoF'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='oSne3o6dZ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='yRqAlsSzVts'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='E2rLKdM60'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='wMNkyQZB'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='OTWux4ECOq5s'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='BE2eE1AYXq'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='D6Lccp'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='BiFypXD'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='pWE4jpiO'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='PepmHmv'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='5WSSOTxmQ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='UTtNmIa'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='RO3DyPO'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='WP65CZKLK'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='MkMTvVcvsjMD'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='a9zxfkFEpxUj'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='v7B04vKKjK'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='1E7ZVtm5'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='REEW1Gl8U8K'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='cNXMmEE93P'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='gClVqyfo'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='aTSpiAreH6'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='lcpAp9damJ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ZZZfkqVNUUtI'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ZbCrdnsT6rPg'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='mJozqZN7C5F'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='SL4I0Y'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='R40ZR0c'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='eZs7SJtZrCgl'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='hPMBt5hNZlr'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='kqdufNgE'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='BJgzTk'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='zsAOxDz'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='RDxeZOu'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='DeHuyp'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='GXYc2qcLL7'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='34qSnK8oF'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='zBhyWrAcU8'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='pEbAOlz'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='SEVWo4qziB9i'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='7s03143mrw'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='KmSlV0qHrq'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='4GliqZTc9'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='DgnRpJ3MB8l'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='NH6A26MfxqWR'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='NFy5RmjNI'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='XHYizYe'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='7hTOev'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='jitHV7'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ENEVrLqh'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='FvB2n3bSKCa2'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ewDlSX9'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='zlV4zqiy'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='N5ZQddFKJS'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='RxTvdmdGFtL'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='OpX0ZteG'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='62aeZ1v'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='PkW32YqP'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='G0SuH7nC'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ngwqhxe0E7Y'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='vG9pmzxqg9'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='LPuKGY'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='VLkroL4uK'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='llGm403kKI'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Q8Wo3bn'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='PKrZqCxO6sAo'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='LG97jzL'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='6VR66IXcZ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='zub893281Eb'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='3bOFVnC'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ixnbHJDjS'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='wDlWhyWYV'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='qfP8tlS'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Nwa6dozKG'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='gU5mS3M'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='yHgP0Ipx'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='iNRfNg'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='hZtsTu5DM00'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='R1GHxZS2RcYB'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ahn8NHmEyl'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='9HyWx0E8L'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='JHce523ocW80'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ZjCN9D'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='sOvm14Io'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='S23ubElHbo2k'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='l8DCNGeSaM'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='b7Urp2yX'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='LSzkWN3MS1C'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='0s9AIWNIW'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ep3Ah2I'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='nl2SnySn9x'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='GYlTXXZ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='GOpugIY5'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='5RcxTq6w73'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='oFmKj74'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='qkiyFQ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='SenWfmO'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='gW1ia7bM6gh'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='3GkrodNN6N'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='u2EYG2FtpNCK'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='GP08v3B'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Ys64prrx'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='5XDxqn78M'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='0VS3Xn'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Z0HjXfUgzo'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='PBB8Gm'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='nShQOgDp0A92'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='PdmHTWt'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='zMBTKWz'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='FdyXYe0Tm'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='AwVqxyBZ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='TuAj9TTv'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='leCzT9p'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='rEf5v3'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='8EpE1Phvv'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ySgcsklu58'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='HDjUK1OPRM8'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='gSyHGSRkRT'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='JkClSrZvuQS'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='uFBgLMJ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='CBsHbJWmlEz'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='jLAK8j3S4'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='avRRjB0'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='2sRW6U2'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='9q7wLJ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='PLFzxa'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='OtXk6zXeF'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='B6a0Fgd69Hi'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Jt1pcap'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='BWMLMXQpjEI'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='rsebFYH0at'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='noa6ChOv'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='M6XIgsI27AVV'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='dzvBkiqEK3'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='nBPnQpngXQ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='3SGgcehRY'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='9unl0HPio'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='XYytr0R9'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='vW7cSV'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='h8cTqBKEOK'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='MhUXMPHy'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='0haDoONn'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='y3YXi57ymRij'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='XZtxiTL'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='HxVxrP7Sd'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='HDBO8Kr'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='iph0iisBHl'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='cLtvl2ci'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ZQy7FMSYWg5'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='n7SShrAbAVHx'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='kr7dYDJc'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='cUjyH44Itg'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='0XXNtGkA'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='juuWqf'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='LMmA3jh2Jv'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ijfQCRYAeAI'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='AnJtbelBi6nx'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='XSus1gjVGH'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='JwSvfmMXert'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='kCMc7wc4'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='XXlLABRPw0Sy'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='JlYiQh'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='eJ7R75FvC'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='2BzAAzTUFdr'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='GssH3D'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Zh8wQQKG'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='HnShiPk68d'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='qwEOZknh9v'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='OLRVx9QttCR'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='AD1FoHKWiu'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='2YEHffMpIL'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='nNmSViQkWT'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='OVas1RIP8EMw'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Jkw4ygPFtC3'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='SLN62hhoF'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='oKPX3V'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='edAe9tkQf'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='SoylYJcxLy'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Vjc9j2KxHx'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='DK2fMaebSNCa'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='jmAgRkecKLav'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='v22SDI54Y2RG'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='w5jvfmmujyG'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='mSPQG9pI'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='MXQyYJBa'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='qlgeEqjYM'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='YCnGtAJXBM'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='EZsqPm9toi'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='RxZ4ZHTiWFoj'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='F3JaGMEhF'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='mB8wexDZp8R'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='oOyByMJyRjT'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='htD3T4nl'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='267oltPh'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='cZ3vUkfr29ks'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Zk2pBXMLfSIU'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='RlReoP'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Z3SAo5mTzim'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='pIufqXfO'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ORQp4OeXQ0g'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='U8oGe2NYoyB'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='nScmUM'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='nYpQ5tLG2VV'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='MbZNkpm4un'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='M4N9hpzTtJ1'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='IJhylKCkjcw'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='qFtxBx7'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='pZHvGoaGf61'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='kJdUzOowJ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='YEKDeV'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Om9fNdBfT'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='SBbRZb2szKl'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='zU8psTzWo'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='QimrJPX'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='2sVkcEcZEs'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='H90eB49I'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='cqNuJbz'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='qWW3x6'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Q7hjeL0hPLp'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='W6ViM9'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='9QftsFH'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='fTRGNgX'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='CcNQzAd6oswN'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='2QprDEL7ROh'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='zxZJYnPLpUcS'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='easv2wpwQl'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='VmnclaUy5mh3'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='i1oPYQ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='SbXBYip'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='FneeFpJg'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='HuUyYtwhJZHV'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='F4LrxJV'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='SwAGG9s5v5'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='P8mdzM'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='oqv3e8'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='gQxEaPieGOT'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='MqGvR3SGP4xE'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='CVWx4ODBtxu'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='wdQ9F2Eyq'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='q4E2po2'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='G7eCeebz'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='7gJnWR6wC'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='FF2oO8HzPW'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='vJj4UBp'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='dECdF9BmZH'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='8sBfsylnamzK'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ZZ7rEYhEYDe'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='j5QZetBDak'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='1a3SGzKU3M'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='MBZaviQnxZH'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='c0PBy8uAUl'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='cLZt6pDnaTQq'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='YaBVqNFN0S'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='4QfYg6Iuyd'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='YqhACxsqslV'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ZvYstWVODbrJ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='P5KDeGABvS'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='PI6l4o2'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='AjGhAb'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='XUPQQfc'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='XGtcrpz9MO'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='YKN9AdZNn7'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='8Yig4nyMfPXA'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='BlejfmbfK'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='gcT2uABlR8S'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Y6yMJWiZn'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='7rrQQtD5q'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='6MEXXy'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='dliMgk'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='5dY1qnT5Cz'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='AGow1U5Vw'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Jn8dYW'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='HwYnZAx6cS5'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='UoXKfWMtiM'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='S8cLJAO1'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='4qz14X2'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='3JDEA9'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='MEtmFZiNU44'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='kqAxUHBZ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='o3O9wv2R7QMY'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='CKp1rFJTEh'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Kk8jAvGmEPp7'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='KkB63DsvOPWw'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='fEZl9gTmP'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='u3FSruYZ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='mYPtHVSl'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='g2d48yvTze'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='P2BBTASyf'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='6VKu4hFd0G7'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='TMww0fE'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='8BFEXFGaGk5l'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='N1C5f6'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='SpPisSY6'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='oydKivfpmCB'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='NCNGeBS2'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='3KSB8n'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='yC3Eoawg'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='VT4WMw'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='htyo38q'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='JrWqK9I7Utqb'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ZQI3k7YlAV'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='IDh4LFQEIp'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='7hplYoclF'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='U6vEgca2'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='2I7HljD'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='zRBPi8Yv'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='UPNODlACv0Z'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='SEi4kUn'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='njoQr6jj'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='TXSrD98'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='p9ZygI'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='xzRBD43kg'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='AgWcnudkUT'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='tpoPOjkaFVX'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='6WbZFlHdZ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='F3C4LCvp0c'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='gducD3kco8SA'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='hf0FBOm'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Urmnc0hO'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='PVm4iCEkT'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='iRV3DwTl'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='HjpB0u71ZeO'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='0mecUV'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='hhHXx8lNaUR'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='DbPPB1p5TnrG'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='lXCXPH'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='WHdOD4rA'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='HcsT6v32nkMX'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='uJhDPxUvOCLg'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Dr6o9zid1'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='RPDWwJvPzuei'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='7LftNLv1HpMO'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Y3pXofkdnuF'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Vo9PczNxbAK'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='iqA5Tp'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='3KDgJNx6Q3'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Yg6SNN'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='qZzXOBV5c'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='xJ1Y3Nco'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='msL0VTJJ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='9qODELoTqZ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='8MdWNGJVCVN'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='uG7DTs'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='yUGOl9WJBuwN'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='WuHMErxM'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='yf6LYuto'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='UdgxWBIjo'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ZjWuzOdPAwR'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Y4ALRoqT8Y'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='cNEnALUJ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='rYBjylMyWT'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='OgLBkC2Ga'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='CaikG1V'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='OKWAB7'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='4VFWOl'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='MIpzOvvo6ZB'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='sGOKBkrDgH'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='3vIqdU'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='JsWHnnHfwz'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ezAWgDm'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='5uiBvUqX'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='llnHxzKnJv'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='07wO1XK3PI3R'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='2SgSoSfi'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='U2duRwzV'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='61ScrjPuX'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='70bAPjh8t'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='79bH5m9SDC'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='nyW70dBfbdt'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='dH3y2Hq'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='EWtlSc'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='y6hhTF2h'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='HDDmZUAnC'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='0gtdJGIJCi3'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='tKI3qNEQOrp'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='le8Nf4rFth'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Vblqiy4'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='SOsDcn5cq'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='V0MnuqUfS'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='aEojxhZets0g'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='k5ZpA0ZZIGd'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='nBGoMqiJuw9'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='G4fldIo'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Tj2GLtOJk'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='A65w81Muuf'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='VEOH5S4FzUG'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='SJkCm8W4sYgw'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='YxCZGOtLGO7'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='wBXdetFy'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='MmLYis4bWC'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='L6muN2ugB'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='sPolzsVc'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ZAO7u5J'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='mmLUHWw'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='jicptAMpq'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='XIlA8SXp'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='zDUMvlKc'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='GdOYr42qTW9'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Gbfy3iQsih'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='VJgGf3QUZjBz'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='1XLzw4ux'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='a3QVzNwb'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='VE4DSAUJGxbH'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='F5EHCHhAXMF'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ma2EssI'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='5tRkY9RfB'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Wi4Z4APEfJhr'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='aha7S1'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='jlj6yvk'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='J38r4uN'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='uZvvMF'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='vAUmOhzSvd'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='6zAJE7'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='qrH2EL'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='PTnuaIeKv'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Z2mRnJU'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='LzG4y4'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='BPgaMm9'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='uR98HzFxV7'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='aoDuZj'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='v4YP0YF5'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Oj6EXj0'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='C2YETdR'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='gL88HGkDqm'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='pN48uyX'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='lDes3uA'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='7UMjG4B6Dgi'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='NrtNhmC'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='eIEy1fySW5U'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='gxfzTXDfO8YF'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='tRP8Sh'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='zAHGT5OnRnKI'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='twCZDwrYsZm3'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='dfP2KZJ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='RInqmjfkWe3I'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='z3v8CTV'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='2pEi5y9KGd4'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='v83xsf'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='E1657pmP8eZ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='eCxGR7wmB'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='vV55uo3ZMDd'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='pJ2tNNq'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='vG9wkuwtqM'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='uVh4S8nWUQ3s'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ZOhDqJtE'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='LfAZEp2VJaUh'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Cr6djtkG3U4'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Te49sI'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='5jJ0CLe8'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='bWyJqXJ5OqMp'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='y8O3gQfak9Y'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ovYt4uyBj'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='J64b7idAfdX0'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='AfuqS2c'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='NJ5mV4'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='yalJoM'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='12Sgu0umLfuT'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='s4B1z8sXV2i'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ONc8ow06Cm4'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='wlyohL'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='cpklUAFxig'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='EhKybbF9'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Ae0PErg7vDPU'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='jGEvn4'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='rznPsPtKD'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='5opf3o0c2k3d'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='8KkoW3r'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='pSrFgwP0P'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='jQE7kQ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='znixgM'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='pnHjKrS8JMr'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='bovVgC'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='7LIOGpamxu'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='1ztUMC'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='BiipuRnPrI6'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='WmZSh7Ay3Z3j'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='cqe9yyVpqh'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='VG8Ob685j9'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='MYQ8Q9kzp'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Ay7738jYvD'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='rVLF7EQ4kNNW'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='v4Py6suz'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='zJjqgh7xdEI'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='A1p6Ev'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='pJOmTuz'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='5Qi7Zce4NPM'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='k3I1Oj0c'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='BfyysfO'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Q6iL9Ajr'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='2m0WFA32J1bl'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='OrwUe7Gn2lJg'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ypqRILHp'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='TWH4Dv'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='HFLcpfnG0aiZ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='59kclCzgW2Pm'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='IVmZf5SH'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='HqpS8MI4zw'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Ns2N6BYak'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='cR7gp9444'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='dzJwl180Clhe'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='6aHZMKGA'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='CTT5jcPRC9'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='7RqnZwdZWO'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='RXcGoL'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='RXssWxB1'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='VHojCeaLahw'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='1pzf5Wzk4H'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='YSpM7d67vK'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='74ErUmZVlCws'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Y7UrMG7Q'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='1NMSgtsj'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='lXqDi6QS'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='tL4g3eCR'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Qv8tMKaANNL'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='PS2jOS'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='xJW83o'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='oXgHnymoyp0f'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='T5cnyQ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='3J1CwQDA'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='PuT9ys9r87'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='9O1h5jrYoP'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='dUS49U'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='a4tXmAm'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='JdrZhEeD0EA'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='VXfles0fSdb'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='NhRmGi'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='qhRw5POYX'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='LHF12yaxQ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='qYYXlhsCDo1'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='2t6UyAosv'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='HXL3pdKML'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='MxZn7l'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='4huLN1cyNqj'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='3ZW4HlWP5'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='P3LGGz'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='fYHcc78m016i'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='TMuPsoHBm6F'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='KPU9pi'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='7agxqyTJ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='eoahQDbvMRZ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='PP5O2UVjZbE'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='0XZGGg6w'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='cpy1ofULof'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='SsbatAgscbV'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='LhvrRT'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='tqux6DZsyIi'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='e6V12gJFiVga'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='KmuzfOgr7TF'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='6F4RsMnwEW'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='qsth2Dyzagf'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='n3mEvDDl'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='9fUaojKfp'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='eeeTsg'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='GYBhSnmDu6tS'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='zh6IV4YhZmAR'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='j1os3O'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='9qIhxR'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='IqdIQKLrBb'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='IIC3zM7JjuuC'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ZFyGN4wVN'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='aMbRYZQ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='GqwP2gNtDs'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='BqKRFyM1WUz'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='0rfwpV9Xpml'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='GYCRX4r6'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='GgWh4DyK5R0'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='TycKnp'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='orOGvRq8Do'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='X4hir5L'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='mr6QWClutK'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='7E75TuEM92BA'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='6YY1mClN'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='GQclYj'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='D4AOQpoZbPY'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='MaE5wnYWH'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='FYbOFCytoY'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='BceLnNwhWz0'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='m3gKtuCBrhYy'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='qxfunt4kK'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='4PEajAkZ2'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='i3N6A3HU47rp'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='TLZUYXxbWGl4'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='C8Nmzd'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='U18eQY9H'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='7qc1az3QAa'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='lx6NbjdRu'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='h9iEvPg8kDrv'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='m2Vkd0'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='OC5bzQ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='mw61XY6WRXmd'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='2v2OWa89F'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='GJYOVBlPEb'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='e7CjIx9USbtt'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='lYQHbC'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ll909wQs6N5H'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='4wZ4sXPafLW2'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='nLhKCcCFSvt'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='iCtjrI'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='PaJdGN'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='SOzQA7aWpo'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='MEcWCP0cE'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='XS6gQBL7Tf'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='iTqbcufwb'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='jsorqUJhRrpx'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='2pFFGe'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Y8GtCNqE'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ChO7GmQEE'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='pLbeo8J'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='n771mkH2TIQC'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='dCpt4tV8'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='GFLif6UT51Xr'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='oNOCzeSWFM3a'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='XL2TlC'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='T0285XI'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='erMDKJz4NTJ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='PumqotSF5kjj'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='WF5hpKvFXw'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='3qIgpHSM5'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='yDntBAw'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='zxjSdVa'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='EUadidHwF'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='sgPcDueFU'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='6XIFWDxZ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='r2X6kM8I'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='3o80gybVoxpw'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='zJ6oFV'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='jynrwy'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ITot1I0IJBJ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='4eqy7jH5PSxp'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='LOk1CapOeYx'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='mzsbkPSArV'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='j1GaHfcwDTLw'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='qX40Ii0'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='DiLhtv'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='EeeB2VnQe4'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='l4NbRwY3jLBV'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='6o5VGS9a'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='M1QbwnL5KUC'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ZXDT485Mqzg'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='mwQsOp6XI'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='IXGkNEA9ep4H'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='hpKxn5Kq'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Gy14wBlY'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='CmxFHmnIHal'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='nHVEPiFjVGP'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='xYwJAk'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='6zufHk'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='AiaixIULwrS'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='d23uv8IxD89'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='hL4IRo4P49Sd'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='smiezogxBDPy'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='HUqvl35y4'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='dYa9sh'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='71nrVEGSbfKn'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='LL3g2Pw'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='psHQpHXq4NI3'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='2o83CpRPLHw'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='tWt44NqO'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='zcDrJxHOF'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='smjVK5HOgSQ9'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='zy3XmG'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='oVIOqJwiF'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='h6ANNLL5JN'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='wo8Gif'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ADniQW1'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='sJ4uE7kDQ5by'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='p57o5x'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='pHcPllTElO'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='SEfpLU6ZRl'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='SnZoLhtSMGG'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='k3bqBTdWlfE'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='9EiAr8grSQvM'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='sZgtT9W4l'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='mFJjZMgx3dnc'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ishvafEY1Mc'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='xa7R1x'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='JK2MhE98q'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='1MGJO6TDA7n'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='YZwSB6'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='60TlhwV1a7F'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='26uBIu76'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='24Pf4of3ZaQ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='AnLQb6Dj92uS'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='HWCSWPKQD'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='3PEDPBC'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='VWpA1GNsZWfI'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='LQ87WMHR8c5'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='YZiB8orwLG'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='GmkHlTtkXZ1'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Dtrqd4a1rj'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ZAAy8AWrZN9f'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='sK3aRHfLc'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='cqU6MfutMrT'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='OSoXUv0y'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='4u1uCP'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='XIQ4kfrdoTu'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='dJ0SOTER8BD'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='KuUQfe'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='rR0aCQvp7kur'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='80ecueTlWyuI'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='MgtFhCyf9y'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='k2sUSDuL'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='o0JobWXjUM9w'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='zzBCwXJ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='jefklt2l'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='B5lI8Gujo'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='jOsIDC'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='QhfnMi'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='SHHT1o'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='9dPkulW'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='KnYQ33'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Leb1piMa'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='viBYzeNHc'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='QKEvO7Xhm'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='22g5EwNmfy'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='H64LULJ589'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='b9nd9QSG'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='O4lv2M0'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='FWXXgA'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='RORlHAMmOa'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='LMRSJH89'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='8WTAhB27gCr'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='AvA9wU7qFWR'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='rl9gRCde'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='jYpcQCUcKA'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='yon21ZR'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Y8sv2lm'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='yXg4pk3u1Ick'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='M4yAlJn'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='r8JWr9t'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='EwQxmZr'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='5hLgJXTna'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='FgxedLgKh'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='LxUd66V60GcC'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='gPXCPCVmv7'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ijE1OjnF2p9'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='1Mnpx7LqhpV'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='nHfLtNPi'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='spjLyiNFjMv'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Ff5r0a62WNYp'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='oZ2psLToH'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='NwFXCM'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='tfSYpREkPhM0'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='3Xu3HQCqk'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='helPGi'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='i8cvfeNx'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='fTst9X2AgNrh'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Y0CjXyRXbw'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='EDNceEt'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='g04ZKoI77pwD'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='XeaHUg8ErpQV'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Q5qhvBO'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Fle2opb7qYS7'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='uq0Pv2IFSL'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='aZ3Dvx5xFW'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='i47suebqw'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='r4Tpj3RazPR'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='zPEGf49Oimn'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='RFEZ1iRSXViA'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Mv2T41so4'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='PbsBonJ0oL18'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='liyADz'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='FDBB59vKT'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ldUdtexm'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='GgxmSd'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='hCAIKC'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='BHsNZIfuvC'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='KOCYaWywyKDJ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='grf7OO4r'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ZQPvq5aCV'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='OZlGqpyNux'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='WLKHj2'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='jJvBqnd'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='8UoTfswDk4lR'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='YkQ5YE'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='1REy2F'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='MBkHYT9q'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='yXBYfVdmLTM'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='emVdlv'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='uEq8GojMACx'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='TzyJ8QMsJOis'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='yMgo3Rq'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='ogEgHxUt'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='RMNhFnu2GjDi'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='U0Mkx4'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='EPn655AeEL'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='fw0L2n'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Upcjwn'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='UHC0XgShCS'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='5Gt2vYRSffU2'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='nfXshI'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='GfSjMwZxTK0L'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='R5dWUUzpNE'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='YnltWrzx'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='sGGA6w2JgMd'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='KrwbKwD0y'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='DMyNiQb7Lb'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='eGQOXDQcJtCU'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='8nGeBzD'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Ae2EY56'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='IGuPOuMC'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Lcq9Jwbwt4gG'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='Swma7i8N9'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='d8iLO5I5tekd'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='5xeyMU'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='6XpG6GDYMSO'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='TEsvKyN'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='GxMu0kUQ9'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='rvd3TWoB'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='XoIEkYfm'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='IoIwDt8'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='WWfwd3'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='YgnLeyhvK'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='i4FoohLY6Kk'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='hNrNuvNrc'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='taacAMOzttif'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='NeXsxn'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='kQtMdIJOUJ'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='1NRNYG'WHERE ID = @counter;
SET @counter = @counter + 1;
UPDATE players SET password ='goQ0pNePwa'WHERE ID = @counter;
SET @counter = @counter + 1;
